import logging
import copy
import sys
from cbnetwork.cbnetwork import CBN
from cbnetwork.directededge import DirectedEdge
from cbnetwork.internalvariable import InternalVariable
from cbnetwork.localnetwork import LocalNetwork
from cbnetwork.utils.customtext import CustomText

# 1. Setup Logging - Keep it focused
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    stream=sys.stdout
)

def create_base_networks():
    # Network 2: Source (Variables 6-10)
    d_net2_vars = {
        6: [[-6]],
        7: [[7]],
        8: [[8]],
        9: [[9]],
        10: [[10]],
    }
    ln2 = LocalNetwork(2, [6, 7, 8, 9, 10])
    for v, cnf in d_net2_vars.items():
        ln2.descriptive_function_variables.append(InternalVariable(v, cnf))

    # Network 1: Destination (Variables 1-5, depends on Signal 11)
    d_net1_vars = {
        1: [[1], [11]],
        2: [[2, 11]],
        3: [[3, 11], [-3, -11]],
        4: [[4]],
        5: [[5]],
    }
    ln1 = LocalNetwork(1, [1, 2, 3, 4, 5])
    for v, cnf in d_net1_vars.items():
        ln1.descriptive_function_variables.append(InternalVariable(v, cnf))

    # Signal 11 = 6 AND 7
    coupling_edge = DirectedEdge(
        index=1,
        index_variable_signal=11,
        input_local_network=1,
        output_local_network=2,
        l_output_variables=[6, 7],
        coupling_function=" 6 ∧ 7 "
    )
    
    return [ln1, ln2], [coupling_edge]

def print_detailed_report(networks, edges, method_name):
    print(f"\n{'='*80}")
    print(f" DETAILED REPORT: {method_name}")
    print(f"{'='*80}")
    
    for net in networks:
        print(f"\n--- LOCAL NETWORK {net.index} ---")
        print(f"  Internal Variables: {net.internal_variables}")
        print(f"  External Variables: {net.external_variables}")
        print(f"  Logic (Variables & CNF):")
        for var in net.descriptive_function_variables:
            print(f"    Var {var.index:2} -> CNF: {var.cnf_function}")
        
        # Output signals from THIS network
        out_signals = [e for e in edges if e.output_local_network == net.index]
        if out_signals:
            print(f"  Output Signals generated by this Network:")
            for s in out_signals:
                print(f"    Signal {s.index_variable} (Index {s.index}): {s.coupling_function} using vars {s.l_output_variables}")

        print(f"  Attractors per Scene:")
        for scene_obj in net.local_scenes:
            scene_str = "".join(scene_obj.l_values) if scene_obj.l_values else "None"
            print(f"    Scene [{scene_str}]: {len(scene_obj.l_attractors)} attractors found")
            for i, attr in enumerate(scene_obj.l_attractors):
                states = ["".join(str(v) for v in s.l_variable_values[:len(net.internal_variables)]) for s in attr.l_states]
                # Show only first few attractors if many, but here we have few
                print(f"      Attr {i+1:2}: {states}")

# --- EXECUTION ---
l_nets, l_edges = create_base_networks()

# 4. RUN BRUTE FORCE
nets_bf = copy.deepcopy(l_nets)
edges_bf = copy.deepcopy(l_edges)

for net in nets_bf:
    input_signals = [e for e in edges_bf if e.input_local_network == net.index]
    net.process_input_signals(input_signals)

LocalNetwork.find_local_attractors_brute_force(nets_bf[0], local_scenes=[['0'], ['1']])
LocalNetwork.find_local_attractors_brute_force(nets_bf[1], local_scenes=[[]])

# 5. RUN SAT
nets_sat = copy.deepcopy(l_nets)
edges_sat = copy.deepcopy(l_edges)
for net in nets_sat:
    input_signals = [e for e in edges_sat if e.input_local_network == net.index]
    net.process_input_signals(input_signals)

o_cbn = CBN(nets_sat, edges_sat)
o_cbn.find_local_attractors_sequential()

# 6. SHOW DETAILED REPORTS
print_detailed_report(nets_bf, edges_bf, "BRUTE FORCE METHOD")
print_detailed_report(o_cbn.l_local_networks, edges_sat, "NORMAL (SAT) METHOD")

# 7. FINAL COMPARISON
def extract_summary(networks):
    s = ""
    for n in sorted(networks, key=lambda x: x.index):
        s += f"Net{n.index}:"
        for sc in sorted(n.local_scenes, key=lambda x: "".join(x.l_values)):
            s += f" Scene{''.join(sc.l_values)}:{len(sc.l_attractors)}attractors;"
    return s

bf_sum = extract_summary(nets_bf)
sat_sum = extract_summary(o_cbn.l_local_networks)

print(f"\n{'='*80}")
if bf_sum == sat_sum:
    print(" SUMMARY: Both methods are 100% consistent.")
else:
    print(" SUMMARY: MISMATCH detected!")
print(f"{'='*80}\n")
